config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'activities', to: 'users/registrations#new_activity'
    post 'activities', to: 'users/registrations#create_activity'
    post 'guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: "cards#index" 
  
  resources :users, only: [:show,:edit,:update] do
    collection do
      get 'search'
    end
  end
  resources :cards, only: [:index,:new,:create,:edit,:update] do
    post 'like' => 'likes#create'
    delete '/like' => 'likes#destroy'
  end
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :card
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like

  def create
    # binding.pry
    card = Card.find(params[:card_id])
    like = Like.create(user_id: current_user.id,card_id: card.id)
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    # binding.pry
    card = Card.find(params[:card_id])
    like = Like.find_by(user_id: current_user.id,card_id: card.id)
    like.delete
    redirect_back(fallback_location: root_path)
  end

  private
  def set_like
    @card = Card.find(params[:card_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<%# ほっこりボタン機能 %>
  <% if card.liked_by?(current_user)%>
    ほっこり
    <%= link_to  card_like_path(card), method: :delete  do%>
    <i class="fas fa-star"></i>
    <% end %>
  <% else %>
    ほっこり
    <%= link_to  card_like_path(card),method: :post do %>
      <i class="far fa-star"></i>
    <% end %>
  <% end %>
  <%= Like.where(card_id: card.id).count%>