config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'activities', to: 'users/registrations#new_activity'
    post 'activities', to: 'users/registrations#create_activity'
    post 'guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: "cards#index" 
  
  resources :users, only: [:show,:edit,:update] do
    collection do
      get 'search'
    end
  end
  resources :cards, only: [:index,:new,:create,:edit,:update] do
    post 'like' => 'likes#create'
    delete '/like' => 'likes#destroy'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :nickname, presence: true

         has_many :cards
         has_one :activity , dependent: :destroy
         has_many :receive_cards
         has_many :send_cards
         has_one_attached :image
         has_many :likes, dependent: :destroy
         has_many :like_cards, through: :likes,source: :card


         def self.search(search)
          if search != ""
            User.where('nickname LIKE(?)', "%#{search}%")
          else
            User.all
          end
         end
         
         def self.guest
          find_or_create_by!(nickname: "ゲスト",email: 'guest@example.com') do |user|
            user.password = SecureRandom.urlsafe_base64
          end
         end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
  end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      render :new and return
    end
   session["devise.regist_data"] = {user: @user.attributes}
   session["devise.regist_data"][:user]["password"] = params[:user][:password]
   @activity = @user.build_activity
   render :new_activity
  end

  def create_activity
    @user = User.new(session["devise.regist_data"]["user"])
    @activity = Activity.new(activity_params)
    unless @activity.valid?
      render :new_activity and return
    end
    @user.build_activity(@activity.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
    redirect_to root_path
  end
  # binding.pry
 
  private
 
  def activity_params
    params.require(:activity).permit(:depertment_id,:philosophy_id,:hobby,:good_thing)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path
  end
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_current_user, only: :edit
  before_action :guest_user_auth,only: :edit
  
  def show
    @user = User.find(params[:id])
    @card = Card.new
    @receive_cards = @user.receive_cards.includes(:user,:card).order("created_at desc")
    @send_cards = @user.send_cards.includes(:user,:card).order("created_at desc")
    @guest_user = User.find_by(email:'guest@example.com')
  end


  def edit
    @user = User.find(params[:id])
    @activity = Activity.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @activity = Activity.find(params[:id])
    
    @user.update(user_params)
    @activity.update(activity_params)
    # binding.pry
    redirect_to root_path
  
  end

  def search
    @users = User.search(params[:keyword])
  end
  
  private

  def user_params
    params.require(:user).permit(:nickname,:image)
  end
  
  def activity_params
    params.require(:activity).permit(:depertment_id,:philosophy_id,:hobby,:good_thing)
  end

  def ensure_current_user
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to root_path
    end
  end

  def guest_user_auth
    @guest_user = User.find_by(email:'guest@example.com')
    if current_user == @guest_user
      redirect_to root_path
    end
  end
  

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
     <div class="col-md-8 offset-md-2">
      <div class="card edit p-5">
        <h1 class="page-heading">ThanksCards</h1>
        <h2 class="page-heading">編集ページ</h2>

        <%= form_with  model: @user, url: user_path do |f| %>

          <div class="field">
            <%= f.label :image,"画像・サムネイル" %><br />
            <%= f.file_field :image, class: "form-control-file mb-3" %>
          </div>

          <div class="field">
            <%= f.label :nickname ,"ニックネーム・名前"%><br />
            <%= f.text_field :nickname, autofocus: true, autocomplete: "nickname",class: "form-control mb-3" %>
          </div>

          <%# activityモデルのフォーム %>
          <%= fields_for @user.activity do |activity_f| %>
            <div class="field">
              <%= activity_f.label :depertment_id,"所属部署" %><br />
              <%= activity_f.collection_select(:depertment_id, Depertment.all , :id, :name, {}, class: "form-control mb-3") %>
            </div>

            <div class="field">
              <%= activity_f.label :philosophy_id ,"好きな企業理念"%><br />
              <%= activity_f.collection_select(:philosophy_id, Philosophy.all , :id, :name, {}, class: "form-control mb-3") %>
            </div>
            
            <div class="field">
              <%= activity_f.label :hobby,"趣味・好きなもの" %><br />
              <%= activity_f.text_field :hobby, class: "form-control mb-3" %>
            </div>

            <div class="field">
              <%= activity_f.label :good_thing,"最近あった良かったこと" %><br />
              <%= activity_f.text_area :good_thing,class: "form-control mb-3",placeholder: "どんな事がありましたか？" %>
            </div>
          <% end %>
          <%# activityモデルのフォーム %>

            <div class="actions">
              <%= f.submit "保存",class: "btn btn-info btn-lg w-100 mb-4", id: "save-btn" %>
            </div>
        <% end %>
        <div class="row">
          <div class="col">
            <%= link_to "メインページへ", root_path,class: "btn btn-warning btn-md w-100 mb-4"%>
          </div>
          <div class="col">
            <%= link_to "#{current_user.nickname}さんのページへ", user_path(current_user),class: "btn btn-success btn-md w-100 mb-4"%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/search.html.erb
<%= render "shared/header" %>

<div class="container main">
  <div class="row">

    <div class="col-lg-4">
      <h1 class="my-4">カードを<br>贈ってみよう</h1>
      <%# 検索フォーム %>
      <%= form_with(url: search_users_path, local: true, method: :get,class: "d-lg-inline-block form-inline my-2 mw-100") do |form| %>
        <%= form.text_field :keyword, placeholder: "贈りたい相手を探そう", class: "form-control bg-light  mr-2" %>
        <%= form.submit "検索", class: "btn btn-info" %>
      <% end %>
      <%# ユーザー名と詳細ページへの遷移、ランダムに３人%>
      <div class="list-group mb-1">
        <% @users.where.not(id: current_user.id).each do |user| %>
          <%= link_to user_path(user) do%>
            <div class="list-group-item mb-1 ">
              <%= user.nickname%>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <!-- /.col-lg-4 -->

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

<!-- Footer -->
<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="container main">
  <div class="row">
    <div class="col-6">
      <% if @user == @guest_user%>
        <h1 class="text-uppercase font-weight-bold text-dark">ゲストさんのページ</h1>
      <% else %>
      <%# 画像添付予定 %>
        <div class="image-field">
          <% if @user.image %>
            <%= image_tag @user.image.variant(resize: "350x200"), class: "img-thumbnail" if @user.image.attached?%>
          <% end %>
        </div>
        <table class="table table-bordered table-active">
          <tbody>
            <tr>
              <th scope="col">ニックネーム・名前</th>
              <td><%= @user.nickname %></td>
            </tr>
            <tr>
              <th scope="row">所属部署</th>
              <td><%= @user.activity.depertment.name%></td>
            </tr>
            <tr>
              <th scope="row">好きな企業理念</th>
              <td><%= @user.activity.philosophy.name%></td>
            </tr>
            <tr>
              <th scope="row">趣味・好きなもの</th>
              <td><%= @user.activity.hobby%></td>
            </tr>
            <% if @user.activity.good_thing%>
              <tr>
                <th scope="row">最近あった良かったこと</th>
                <td><%= @user.activity.good_thing%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
    <!-- /.col-lg-6 -->

    <%# 現状余白 %>
    <div class="col-1"> </div>
    <!-- /.col-lg-2 -->


    <%# 詳細ページからでもカードを贈れるor編集、カードをもっと見るページ %>
    <div class="col-5">
      <% if @user == @guest_user%>
        <h3 class="text-uppercase font-weight-bold text-dark">受け取ったカード<br> 贈ったカードが閲覧できます</h3>
      <% else %>

      <% if user_signed_in? && current_user.id == @user.id %>
        <%= link_to '編集ページへ', edit_user_path , method: :get, class: "btn btn-dark" %>
      <%else%>
          <div class="form-wrapper">
            <%=form_with model: @card,url: cards_path, local: true do |f|%>
              <div class="field">
                <%= f.label :content,"#{@user.nickname}さんへのメッセージ" %><br />
                <%= f.text_area :content,placeholder:"ありがとう＾＾",rows:"5" ,maxlength:"300",class: "form-control mb-3"%>
              </div>
              <input name="card[receive_user_id]" type="hidden" value = <%=@user.id%> />
              <div>
                <%= f.submit "カードを贈る",class: "btn btn-info btn-lg w-100 mb-4" %>
              </div>
            <% end %>
          </div>
      <% end %>

    <% end %>
    </div>
    
    <!-- /.col-lg-4 -->

  </div>
  <!-- /.row -->

</div>
<!-- /上部 ユーザー情報/余白/送信フォーム -->

<div class="container">
  <div class="row">
    <div class="col-6">
      <h4>受け取ったカード</h4>
      <div class="row row-cols-1 row-cols-xl-2">
        <% @receive_cards.first(16).each do |receive_card|%>
          <div class="col-xl-6 mb-4">

            <div class="card h-100">
              <% if receive_card.card.send_user.image %>
                <%= image_tag receive_card.card.send_user.image.variant(resize: "350x200"), class: "img-thumbnail card-img-top" if receive_card.card.send_user.image.attached?%>
              <% end %>
              
              <div class="card-body">
                <%= link_to user_path(receive_card.card.send_user) do%>
                  <div class="card-title">
                    From:<%= receive_card.card.send_user.nickname%>
                  </div>
                <% end %>
                <p class="card-text"><%= receive_card.card.content%></p>
              </div>
              <div class="card-footer">
                <%= render partial: "likes/like",locals: {card: receive_card.card}%>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <%# <%= link_to "もっと見る", "#"%>
    </div>

    <div class="col-6">
      <h4>贈ったカード</h4>
      <div class="row row-cols-1 row-cols-xl-2">
        <% @send_cards.first(16).each do |send_card|%>
          <div class="col-xl-6 mb-4">
            <div class="card h-100">
              <% if send_card.card.receive_user.image %>
                <%= image_tag send_card.card.receive_user.image.variant(resize: "350x200"), class: "img-thumbnail card-img-top" if send_card.card.receive_user.image.attached?%>
              <% end %>
              <div class="card-body">
                <%= link_to user_path(send_card.card.receive_user) do%>
                  <div class="card-title">
                    To:<%= send_card.card.receive_user.nickname%>
                  </div>
                <% end %>
                <p class="card-text"><%= send_card.card.content%></p>
              </div>
              <div class="card-footer">
                <%= render partial: "likes/like",locals: {card: send_card.card}%>
                <% if user_signed_in? && current_user.id == send_card.user_id %>
                  <%= link_to "編集",edit_card_path(send_card.card),class: "btn btn-outline-dark btn-sm float-right" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <%# <%= link_to "もっと見る", "#"%>
    </div>  

  </div>
</div>
<!-- /下部 カード表示 -->

app/views/users/update.html.erb
保存完了