config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'activities', to: 'users/registrations#new_activity'
    post 'activities', to: 'users/registrations#create_activity'
    post 'guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: "cards#index" 
  
  resources :users, only: [:show,:edit,:update] do
    collection do
      get 'search'
    end
  end
  resources :cards, only: [:index,:new,:create,:edit,:update] do
    post 'like' => 'likes#create'
    delete '/like' => 'likes#destroy'
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to_active_hash :depertment
  belongs_to_active_hash :philosophy

  belongs_to :user,optional: true 
  #外部キーがnilであることを許可する、ウィザード形式なので入力時は外部キーが無いため

  validates  :depertment_id, numericality: { other_than: 1 ,message: 'must be selected'} 
  validates  :philosophy_id, numericality: { other_than: 1 ,message: 'must be selected'}
  validates :hobby,presence: true

  # def self.guest_activity
  #   user =  User.find_by(email:'guest@example.com')
  #   @activity = find_or_create_by!(depertment_id: 2,philosophy_id:3,hobby:"ごはん",good_thing:"ゲスト")
  #   user.build_activity(@activity.attributes)
  #   user.save
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord

  validates :content, presence: true

  belongs_to :send_user, class_name: "User"
  belongs_to :receive_user,class_name: "User"
  
  has_many :likes
  has_many :users, through: :likes

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/models/depertment.rb
class Depertment < ActiveHash::Base

  self.data = [
    { id: 1, name: "---"},
    { id: 2, name: "開発部" },
    { id: 3, name: "生産管理部"},
    { id: 4, name: "設計部"},
    { id: 5, name: "経理部"},
    { id: 6, name: "経営企画部"},
    { id: 7, name: "人事部"},
    { id: 8, name: "開発部"},
    { id: 9, name: "総務部"},
    { id: 10, name: "広報部"},
    { id: 11, name: "その他"}
  ]
  
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :card
end

app/models/philosophy.rb
class Philosophy < ActiveHash::Base

  self.data = [
    { id: 1, name: "---"},
    { id: 2, name: "経営理念" },
    { id: 3, name: "行動指針"},
    { id: 4, name: "提供価値"},
    { id: 5, name: "社訓"},
    { id: 6, name: "ビション"},
    { id: 7, name: "組織理念"},
    { id: 8, name: "自立志向"},
    { id: 9, name: "共に楽しむ"},
    { id: 10, name: "ファンを創る"},
    { id: 11, name: "世界を救う"},
    { id: 12, name: "夢を描く"},
    { id: 13, name: "1番を目指す"},
    { id: 14, name: "ユーザー目線を意識する"},
    { id: 15, name: "健康を意識する"},
    { id: 16, name: "ワガママである"},
    { id: 17, name: "チャレンジを楽しむ"},
    { id: 18, name: "アップデートし続ける"},
    { id: 19, name: "その他"}
  ]
  
end

app/models/receive_card.rb
class ReceiveCard < ApplicationRecord
  belongs_to :user
  belongs_to :card
end

app/models/send_card.rb
class SendCard < ApplicationRecord
  belongs_to :user
  belongs_to :card
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :nickname, presence: true

         has_many :cards
         has_one :activity , dependent: :destroy
         has_many :receive_cards
         has_many :send_cards
         has_one_attached :image
         has_many :likes, dependent: :destroy
         has_many :like_cards, through: :likes,source: :card


         def self.search(search)
          if search != ""
            User.where('nickname LIKE(?)', "%#{search}%")
          else
            User.all
          end
         end
         
         def self.guest
          find_or_create_by!(nickname: "ゲスト",email: 'guest@example.com') do |user|
            user.password = SecureRandom.urlsafe_base64
          end
         end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:nickname])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  before_action :ensure_current_user, only: [:edit,:update]

  def index
    @users =User.all       #order("created_at desc") 降順に切り替え用
    @cards = Card.includes(:receive_user,:send_user).order("created_at desc")
    
  end
  
  def new
    @card = Card.new
  end
  
  def create
    @card = Card.new(card_params)
    if @card.valid?
      @card.save
      SendCard.create(user_id: @card.send_user_id,card_id: @card.id)
      ReceiveCard.create(user_id: @card.receive_user_id,card_id: @card.id)
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    # @card = Card.find(params[:id]) before_actionの為コメントアウト
  end

  def update
    # @card = Card.find(params[:id]) before_actionの為コメントアウト
    if @card.update(card_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def card_params
    params.require(:card).permit(:content,:receive_user_id).merge(send_user_id: current_user.id)
  end

  def ensure_current_user
    @card = Card.find(params[:id])
    if current_user.id != @card.send_user_id
      redirect_to root_path
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like

  def create
    # binding.pry
    card = Card.find(params[:card_id])
    like = Like.create(user_id: current_user.id,card_id: card.id)
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    # binding.pry
    card = Card.find(params[:card_id])
    like = Like.find_by(user_id: current_user.id,card_id: card.id)
    like.delete
    redirect_back(fallback_location: root_path)
  end

  private
  def set_like
    @card = Card.find(params[:card_id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController


  def create
    @room = Room.new(room_params)
    if @room.save
      @card = Card.new
      # binding.pry
      redirect_to new_room_card_path(@room)
    else
      render :index
    end
  end


  private

  def room_params
    params.require(:room).permit(:name,user_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_current_user, only: :edit
  before_action :guest_user_auth,only: :edit
  
  def show
    @user = User.find(params[:id])
    @card = Card.new
    @receive_cards = @user.receive_cards.includes(:user,:card).order("created_at desc")
    @send_cards = @user.send_cards.includes(:user,:card).order("created_at desc")
    @guest_user = User.find_by(email:'guest@example.com')
  end


  def edit
    @user = User.find(params[:id])
    @activity = Activity.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @activity = Activity.find(params[:id])
    
    @user.update(user_params)
    @activity.update(activity_params)
    # binding.pry
    redirect_to root_path
  
  end

  def search
    @users = User.search(params[:keyword])
  end
  
  private

  def user_params
    params.require(:user).permit(:nickname,:image)
  end
  
  def activity_params
    params.require(:activity).permit(:depertment_id,:philosophy_id,:hobby,:good_thing)
  end

  def ensure_current_user
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to root_path
    end
  end

  def guest_user_auth
    @guest_user = User.find_by(email:'guest@example.com')
    if current_user == @guest_user
      redirect_to root_path
    end
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul class="list-unstyled alert alert-danger">
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message '><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThanksCards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="py-2 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; arigatou products</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-warning text-uppercase fixed-top" id="mainNav">
  <div class="container">
    <%= link_to "ThanksCards", root_path ,class: "main-heading navbar-brand text-uppercase font-weight-bold text-secondary"%>
      <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-info text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <%# Fontawesomeの記述 %>
        <i class="fas fa-bars"></i> 
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item mx-0 mx-lg-1"><%= link_to "ありがとうカードを贈ろう", new_card_path, class: "nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger font-weight-bold text-dark"%></li> 
            <li class="nav-item mx-0 mx-lg-1"><%= link_to "#{current_user.nickname}さんのページ", user_path(current_user),class: "nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger font-weight-bold text-dark"%></li> 
            <li class="nav-item mx-0 mx-lg-1"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete,class: "nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger font-weight-bold text-dark"%> </li>
          <% else %>
            <li class="nav-item mx-0 mx-lg-1"><%= link_to 'ログイン', new_user_session_path,class: "nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %></li>
            <li class="nav-item mx-0 mx-lg-1"><%= link_to '新規登録',new_user_registration_path ,class: "nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" %></li>
          <% end %>
        </ul>
    </div>
  </div>
</nav>