config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'activities', to: 'users/registrations#new_activity'
    post 'activities', to: 'users/registrations#create_activity'
    post 'guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: "cards#index" 
  
  resources :users, only: [:show,:edit,:update] do
    collection do
      get 'search'
    end
  end
  resources :cards, only: [:index,:new,:create,:edit,:update] do
    post 'like' => 'likes#create'
    delete '/like' => 'likes#destroy'
  end
end

app/models/card.rb
class Card < ApplicationRecord

  validates :content, presence: true

  belongs_to :send_user, class_name: "User"
  belongs_to :receive_user,class_name: "User"
  
  has_many :likes
  has_many :users, through: :likes

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  before_action :ensure_current_user, only: [:edit,:update]

  def index
    @users =User.all       #order("created_at desc") 降順に切り替え用
    @cards = Card.includes(:receive_user,:send_user).order("created_at desc")
    
  end
  
  def new
    @card = Card.new
  end
  
  def create
    @card = Card.new(card_params)
    if @card.valid?
      @card.save
      SendCard.create(user_id: @card.send_user_id,card_id: @card.id)
      ReceiveCard.create(user_id: @card.receive_user_id,card_id: @card.id)
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    # @card = Card.find(params[:id]) before_actionの為コメントアウト
  end

  def update
    # @card = Card.find(params[:id]) before_actionの為コメントアウト
    if @card.update(card_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def card_params
    params.require(:card).permit(:content,:receive_user_id).merge(send_user_id: current_user.id)
  end

  def ensure_current_user
    @card = Card.find(params[:id])
    if current_user.id != @card.send_user_id
      redirect_to root_path
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/edit.html.erb
<%= render "shared/header" %>

<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card send p-5">
        <h1 class="page-heading">感謝の気持ちを伝えよう</h1>

          <%=form_with model: @card,url: card_path, local: true do |f|%>
            <%= render 'layouts/error_messages', model: @card %>
            <div class="field">
              <%= f.label :content,"メッセージ" %><br />
              <%= f.text_area :content,placeholder:"ありがとう＾＾",rows:"5" ,maxlength:"300",class: "form-control mb-3"%>
            </div>

            <div>
              <%= f.submit "編集の保存",class: "btn btn-info btn-lg w-100 mb-4" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cards/index.html.erb
<%= render "shared/header" %>

<div class="container main">
  <div class="row">

    <div class="col-lg-3">
      <h1 class="my-4">カードを<br>贈ってみよう</h1>
      <%# ユーザー名と詳細ページへの遷移、ランダムに３人%>
      <%# 検索フォーム %>
      <%= form_with(url: search_users_path, local: true, method: :get,class: "d-inline-block form-inline  my-2 mw-100") do |form| %>
        <%= form.text_field :keyword, placeholder: "贈りたい相手を探そう", class: "form-control bg-light mb-lg-2 mr-2" %>
        <%= form.submit "検索", class: "btn btn-info" %>
      <% end %>
      <div class="list-group ">
        <% @users.where.not(id: current_user.id).shuffle.first(3).each do |user| %>
          <%= link_to user_path(user) do%>
            <div class="list-group-item mb-1">
              <%= user.nickname%>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <!-- /.col-lg-3 -->

    <%# メインラッパー %>
    <div class="col-lg-9">

      <%# 会社の取組・良例共有スペース %>
      <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item">
            <img class="d-block img-fluid" src="https://picsum.photos/900/350" alt="Second slide">
          </div>
          <div class="carousel-item active">
            <img class="d-block img-fluid" src="https://i.picsum.photos/id/962/900/350.jpg?hmac=VU-HEYxLXZf_xAW6Int4368Ppg0alKuPMey_0h2DWFw" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block img-fluid" src="https://i.picsum.photos/id/314/900/350.jpg?hmac=4k_wpfUmAYK8KNs_X8pITqSyZF1C0EzT7y1eyN_v6v8" alt="Third slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <%# ありがとうカードの表示 %>
      <div class="row">
        <% @cards.first(24).each do |card|%>
          <div class="col-xl-4 col-md-6 mb-4">
            <div class="card h-100">
              <% if card.receive_user.image %>
                <%= image_tag card.receive_user.image.variant(resize: "350x200"), class: "img-thumbnail card-img-top" if card.receive_user.image.attached?%>
              <% end %>
              <div class="card-body">
                <%= link_to user_path(card.receive_user) do%>
                  <div class="receive-user-name">
                    To:<%= card.receive_user.nickname%>
                  </div>
                <% end %>
                <h5 class="card-text"><%= card.content%></h5>
                <%= link_to user_path(card.send_user) do%>
                  <div class="send-user-name">
                    <small> From:<%= card.send_user.nickname%> </small>
                  </div>
                <% end %>
              </div>

              <%# ほっこりボタン機能 %>
              <div class="card-footer">
                <div id="card_<%= card.id%>">
                  <%= render partial: "likes/like",locals: {card: card}%>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <!-- /.row -->

    </div>
    <!-- /.col-lg-9 -->

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

<!-- Footer -->
<%= render "shared/footer" %>

app/views/cards/new.html.erb
<%= render "shared/header" %>
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card send p-5">
        <h1 class="page-heading">感謝の気持ちを伝えよう</h1>

          <%=form_with model: @card,url: cards_path, local: true do |f|%>
            <%= render 'layouts/error_messages', model: @card %>
            <div class="field">
              <%= f.label :receive_user_id,"贈りたい相手選んでね" %><br />
              <%= f.collection_select(:receive_user_id,User.where.not(id: current_user.id),:id,:nickname,{ include_blank: ""},required: true,class: "form-control mb-3")%>
            </div>

            <div class="field">
              <%= f.label :content,"メッセージ" %><br />
              <%= f.text_area :content,placeholder:"ありがとう＾＾",rows:"5" ,maxlength:"300",class: "form-control mb-3"%>
            </div>

            <div>
              <%= f.submit "カードを贈る",class: "btn btn-info btn-lg w-100 mb-4" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>